title: Paperboy — La Portería
email: your-email@example.com
description: >
  Blog de tiras cómicas diarias con roller horizontal concatenado y tira del día vertical.
  Proyecto ligero con Jekyll.
baseurl: "/Porteria"
url: "https://albertomaydayjhondoe.github.io"
twitter_username: jekyllrb
github_username: albertomaydayjhondoe

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - paperboy/
  - setup_paperboy_local.sh
  - porteria.venv/
  - Dockerfile
  - docker-compose.yml

# Collections
collections:
  tiras:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "tiras"
    values:
      layout: "tira"
